debug = true
ret2shell_url = ""

[flag.neuro]
salt = ""
prefix = ""

[flag.evil]
salt = ""
prefix = ""

[flag.complete]
salt = ""
prefix = ""

[flag.complete_rev]
salt = ""
prefix = ""

[openai]
base_url = ""
api_key = ""
model = ""
completion_model = ""

[connections.db]
url = "sqlite:///database/database.db"
